### ISSUE TITLE
linwarrior help (genhelp)

### ISSUE THREAD

**Issue by qubodup** [hackcraft-de/linwarrior#7]
I'm trying to figure out whether mouse sensitivity and graphics settings, perhaps starting vehicle can be changed. The doc/README mentions `genhelp`. Is that a standard Linux tool? Or is http://www.frasersoft.net/genhelp/ meant? Or is it something else?

**Comment by hackcraft-de** [comment]
Think it referred to doxygen for generating source code documentation like javadoc but for c++.

Some parameters like vehicle, planet surface and vegetation can be changed in the global.properties file in the data directory. You may like to try some of that that out. 

https://github.com/hackcraft-de/linwarrior/blob/master/data/base/global.properties

Mouse sensitivity cant be changed though. Some other screen, window and ui parameters are given through the commandline in the start-shellscripts in the main directory.

The structures you see in-game are created by OpenMission, a subclass of GameMission. A proper level loader is missing. There is a incomplete example stub for loading batch/shellscript like files in BatchMission. 

https://github.com/hackcraft-de/linwarrior/tree/master/source/de/hackcraft/game
